language: node_js
node_js:
- lts/*
- node
env:
  global:
    secure: y18F9gqzindmuIa+dSheU7gGadSgx0RvAHKoE3M2tVTcfMvGu+nsZ0V38zGT3SaAz0e081/joLNGnHtRnTgEtxUjKRce9u59+rLJ+wiqSieEYTbKecPSMqhTcGrHHA/QMQqwFlspEue2J8qRwO73kcDqfU4HubE5OC9E6/eqCYw6wsM6S+8BdFElyRa4rkr6gTlfHoSMLhvqXE/oafUYv2+ADnruTupGHugQALkrp2nQIiJ42nddX42BnqnEk1lUqG+8+m7OUg6jNkqtcfrnYBldwXHjF+0qEvGtpKG4tivt5iiVTDZPUWwdlMuvRXrKrooVOOAppUQaJQV5DOXn85rF6GK4xrfdQ49aww3IsmpmWakW3leP91cMvRAyWqdH9RLJHrECFGiSoxBrHpSzYqLVE8YN6AiF0L+sA46iErKomqcLfkXjdi9OeUips8wtkyVkHvvN761sW7sixmC/ClwOPyqdUMYjdJDsiobjmSFEFl5TlUw0fTSEaJpL6AWxrlDgpH/VtQbCpvXf4A8ZcozO44DR/Esdb10c3pfqlV03t1hid/ZzJrDahYgZhOWUTJFfeEqcWId2z56+kEI3xXYrc9G7FIqJEL/SY31ettUaBw3inTZohBzpieqxL7mjmOnK1RPAmRhrv8lH131DEOBFGxBhsH6iVQwOjy6YjhY=
before_install:
- npm install -g npm@latest greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
